### ISSUE TITLE
Animation plays on every state change

### ISSUE THREAD

**Issue by giorgi-abashidze** [KaushickSArgekar/spring#3] opened 2020-08-08 15:19 UTC
Animation plays on every setState method call, which i dont want. i want to animate only when GestureDetector onTap happens, any solutions?

**Comment by KaushickSArgekar** [comment] 2021-05-09 15:45
The issue is fixed in the latest spring 2.0 with a lot more added features.
Check it out. (https://pub.dev/packages/spring)

**Closed as completed by KaushickSArgekar** 2021-05-09 15:45 UTC

**Comment by GustavoFigueira** [comment] 2021-05-11 19:55
Same here! And I'm using version `spring: ^2.0.2`

**Comment by KaushickSArgekar** [comment] 2021-05-12 03:26
> Same here! And I'm using version `spring: ^2.0.2`

Have u tried using different controllers?

**Comment by CalvinTp** [comment] 2022-05-08 07:10
Same here, I am also using spring: ^2.0.2 and the animation is still played on each setState
