### ISSUE TITLE
shake animation sometimes slow

### ISSUE THREAD

**Issue by sanalkv** [KaushickSArgekar/spring#2] opened 2020-06-25 08:11 UTC
i have found out that the shake animation becomes slow sometimes. The reverse animation doesn't always animate with the same speed.

**Comment by KaushickSArgekar** [comment] 2021-05-09 15:46
The issue is fixed in the latest spring 2.0 with a lot more added features.
Check it out. (https://pub.dev/packages/spring)

**Closed as completed by KaushickSArgekar** 2021-05-09 15:46 UTC
