### ISSUE TITLE
Create a SpringController rather than GlobalKey

### ISSUE THREAD

**Issue by josh-burton** [KaushickSArgekar/spring#1] opened 2020-04-23 18:54 UTC
Using a GlobalKey to control an animation doesn't feel right. I feel like it's exposing an implementation detail (SpringState) to the user.

What about creating a SpringController instead? Similar to ScrollController, PageViewController etc.

**Comment by KaushickSArgekar** [comment] 2021-05-09 15:47
Added a Spring controller as you asked.

The issue is fixed in the latest spring 2.0 with a lot more added features.
Check it out. (https://pub.dev/packages/spring)

Thanks for the support.

**Closed as completed by KaushickSArgekar** 2021-05-09 15:47 UTC
Labels: enhancement
